### ISSUE TITLE
How to use with existing datastore question?

### ISSUE THREAD

**Issue by kethan** [feathersjs/feathers-elasticsearch#9]
Hi,
How do i use with already used datastore like mongoDB, MySql, etc ?

How do it manages update, delete, etc?

**Comment by daffl** [comment]
@kethan This is a very broad question (and the repository for the [Elasticsearch](https://www.elastic.co/) adapter is probably not the ideal place for it.

Depending on the database you choose you can often just point the connection string to your existing database and the table/collection to the existing one and then use it [as documented](https://docs.feathersjs.com/databases/readme.html).
